### ISSUE TITLE
implement a HA / balancing mechanism with store chunk

### ISSUE THREAD

**Issue by limbo127** [folbricht/desync#101]
hello, at this time, multiple store does not provide high availability mechanism, -s site1 -s site2 exit with connect: connection refused if site1 down. Is it possible to implement some ha fetatures, at this time for example, we must do -s <localbalancer as haproxy> . 

some ideas as  , if store not respond takes the next, and inform that the store is unvailable for a period of time ?  or better, place this store to the end of the store list

Regards Nicolas

**Comment by folbricht** [comment]
The first question would be how that feature could fit into the command line without overloading. It's not a good idea to use the existing `-s` options and fail over between them, since that would change the semantics and become quite confusing. So perhaps it could be encoded into the existing store options like so `-s "<storeA>|<storeB>"` while still allowing multiple `-s` options, with the first taking precedence as is currently the case.

In addition, there may need to be a new flag to perhaps determine the algorithm to use, if there's going to be multiples. As described above, we could start with:

- Try the currently active store
- If there is an error (other than chunk-not-found), make the 2nd one the active store and try again
- When there's N stores in the group, fail the request after N attempts

Other possibilities include round-robin requests, and blacklist a store in the group after a number of failures for an amount of time.

Last thing to decide is what to do on fail-over in terms of notifying the user. Perhaps a warning to STDERR suffices, but it's going to look a little messy with the progress bar also going there.

**Comment by limbo127** [comment]
perhaps add -s <d;dynamicStore>   where dynamicStore can be an external command that return the real store
Nicolas

**Comment by folbricht** [comment]
@limbo127 There's now a first implementation of failover on https://github.com/folbricht/desync/tree/issue-101. It's be great if you could give that a try under real-life load.

To group stores, you just have to provide them like so `-s "http://serverA/|http://serverB"`. It can take any number of stores separated by `|`.

But there are a few caveats:
- The content of the grouped stores needs to be identical. It will not fail over because a chunk is missing.
- You can't use a group as a writable store to chunk into. It's doable, but not sure if it's actually required.

The way the algorithm works currently is as follows:
- Initially it just hits the first store. This is the active store.
- If an error is encountered (other than missing chunk), it'll fail over to the next store and keep using that.
- If another error is encountered it'll again attempt to switch to the next store in the list (or the first).
- If a request fails N times, and N is the number of stores in the group, the failure is returned to the caller, likely leading to program termination.

**Comment by limbo127** [comment]
Hello,
Thanks you very much for this. I’m trying as soon as possible.
Regards
Nicolas

Le sam. 4 mai 2019 à 19:38, Frank Olbricht <notifications@github.com> a
écrit :
