### ISSUE TITLE
question about chunking works

### ISSUE THREAD

**Issue by limbo127** [folbricht/desync#11]
Hello, 
in desync doc, we can read " For example, up to 10x faster than casync if the chunks are already present in the store. If the chunks are new, it heavily depends on I/O, but it's still likely several times faster than casync." 
Can you be more precise as chunking algo works, do you watch in store if chunk is already present to decide to write or conserve the chunk ?  
regards, 
Nicolas

**Comment by folbricht** [comment]
There's a couple of things here:
- During the chunking, it calculates the checksum of the chunk, then checks the store if that particular chunk is already present, and if so it'll move to the next one, bypassing the compression and storage of the chunk. This optimization is meant to reduce I/O load (and a bit of CPU for the compression) and it improves chunking time when you chunk a similar file to what you have in the store already. Most of the time-saving here is due to the reduced I/O

- The main difference to casync is the parallel chunking algorithm. When you run with `-n 10` for example (the default), it'll break the input file into 10 equal parts and run 10 chunkers, one for each part concurrently making the most out of available CPU. While the chunk workers operate independently, worker1 will try to find a sync point with worker2, worker2 with worker3 and so on. If they find a common split point, the earlier worker stops and its chunks end up in the index. Best case, if the file contains regular data, the workers will find common split points with their neighbouring workers quickly and chunking stops. Worst case, they won't find common split points and the first worker needs to go through the whole file. This happens mainly when chunking a large file with all, or large sections of it containing just 0-bytes.

You didn't specifically ask about the extract phase, but there's an interesting optimization in the latest version of desync that may be applicable to some users. When using the `extract` command (and some others like `mount-index`), desync will not request 0-byte chunks from the store at all. It calculates the ID of a chunk of all zeroes during startup, then uses that instead of repeatedly requesting it from a store.

Command | Mostly/All 0-bytes  | "Regular" data
------------ | ------------- | --
make | Slow (worst-case) - Likely comparable to casync | Fast - Parallel chunking
extract | Extremely fast - Effectively the speed of a truncate() syscall | Fast - Done in parallel, usually limited by I/O

**Comment by limbo127** [comment]
thanks for this explanation.
