### ISSUE TITLE
How is the discriminator obtained?

### ISSUE THREAD

**Issue by BDZenix** [folbricht/desync#143]
Both in casync and desync, the chunk cut descriminator return value like this:
![image](https://user-images.githubusercontent.com/16330887/72675894-f1ec8780-3ac5-11ea-8e6a-efbf9bc5dd89.png)

![image](https://user-images.githubusercontent.com/16330887/72675814-bc936a00-3ac4-11ea-985e-9e285fe6b9cb.png)

And I did an experiment, when input 1M (1 *1024*1024), the result is just equals 1M. But when I input 8M (8 * 1024 * 1024), I got 62724856 (about 60M), It's obviously not even close to the input average value.
So why calculate cut point like this?

**Comment by folbricht** [comment]
desync is meant to be compatible with casync and produce the same output/chunks (or close to it), that's why the same value is used. I suspect a single value doesn't scale well to those larger sizes. Even https://github.com/systemd/casync/blob/master/test/test-cachunker-histogram.c in casync stops at 1M.
