### ISSUE TITLE
enhancement : progres bar for make command

### ISSUE THREAD

**Issue by limbo127** [folbricht/desync#21]
Hello, 
is it possible to implement a progress bar to the desync make command ? 
( progress-bar as a percentage x/100  as curl for example )
regards, 
Nicolas Prochazka

**Comment by folbricht** [comment]
It's not as straightforward as for the other commands. `make` is a 2-stage process (first find the split-points to build the index, followed by chopping up the file), each of which runs multiple goroutines. Perhaps it's possible to use a section of the progress bar for the split, and the remaining section for the chopping.

Regardless, progress will not move gradually, but likely jump during the first stage due to the nature of the algorithm used there.

**Comment by limbo127** [comment]
Ok I understand.
We are working with very big file , and the make process can take 1 hours, without any informations. 
Perhaps it is more simple to have an --fake option to make that give a heuristic time ? ( build index and determine how much  chunks must be write , and how much time a chunk takes to be write )

**Comment by charles-dyfis-net** [comment]
Hmm. I could see multiple progress bars:

- Percent chunked (total, may go over 100% if we can't use the work of some of the threads)
- Percent chunks accepted (will have big jumps when we reach sync points)
- Percent chunks written

The first one would actually be useful, for seeing how much wastage there is from the multithreading algorithm.

**Comment by folbricht** [comment]
There are now 2 progress bars. The first, during chunking, can be  a bit choppy due to the parallel nature of the algorithm. When finished, it'll also print the number of chunks produced as well as the number of wasted chunks.
