### ISSUE TITLE
Confusion about catar

### ISSUE THREAD

**Issue by lastrosade** [folbricht/desync#231]
Is catar just a glorified tar file?

When I use the tar command using a `catar` target instead of a `-s castr -i caidx` no compression/deduplication is done.

I am confused as to why the catar format exists, can I archive a castr to catar in order to unpack it using a caidx?

This would be useful to avoid the gigantic directories that windows just can't deal with.

**Comment by folbricht** [comment]
The catar isn't deduplicated, it exists so you can archive a directory (like regular tar) and then chunk it efficiently since the order of files inside the archive is stable. So a caidx is really just the index of a chunked catar file. Some subcommands let you do it in one step, archive a directory into a stream and chunk it in the process, producing an index file (caidx) + chunks in the store.

**Comment by charles-dyfis-net** [comment]
If you're interested in the "why", it would be better to go to the upstream casync design documents and [introductory blog post](http://0pointer.net/blog/casync-a-tool-for-distributing-file-system-images.html); the decision to create a catar format was not made by desync's developers.

**Comment by lastrosade** [comment]
I see. Thanks for the clarification.
