### ISSUE TITLE
chunk id X does not match its hash Y

### ISSUE THREAD

**Issue by limbo127** [folbricht/desync#37]
Hello, 
we are using a lot of desync, and we have some times bad chunk .
desync make -m  "64:256:512" -n 4  -s /data/cache2/store /data/cache2/indexes/file.index /data/file.raw

sometimes we cannot use our images, and a desync verify show  some  chunk id X does not match ...
we can delete wrong chunk but images is lost.
How can we do ? 
- desync make option to verify chunk sha ?
- is it a possible disk issue ? ( ssd hard disk, f2fs partition )

Regards, 
Nicolas Prochazka

**Comment by folbricht** [comment]
I don't think that desync would store a chunk incorrectly, unless it's maybe killed halfway through writing a chunk. Other than that I suspect that perhaps something else is modifying the file or as you said there's a filesystem/disk issue.

As for verifying, would a separate command work? Adding an option to every single command may be a bit messy. So I'm thinking of something along the lines of `desync verify -s <store> index.caibx`

**Comment by limbo127** [comment]
there's no error during desync make process.
what is hapenning if two desync make process are working on the same local
store ?
regards

2018-05-24 17:25 GMT+02:00 folbricht <notifications@github.com>:

**Comment by limbo127** [comment]
thank,
I 'm doing some test today
Regards
nicolas

2018-05-25 3:23 GMT+02:00 folbricht <notifications@github.com>:

**Comment by limbo127** [comment]
desync make -m 64:256:512 -n 3 -s /data/cache2/store /data/c5df8a5cdd1e6e26fd7ce210c5bbf758.6e4cd4c9-5e8b-4ada-98ea-0b4643370eeb.index /data/c5df8a5cdd1e6e26fd7ce210c5bbf758.6e4cd4c9-5e8b-4ada-98ea-0b4643370eeb.raw



data to be stored does not match expected hash 91ba20c831c892fa32b6b7e8f2e2b3264bb4605b71c9269b77b5f88f8a5dddd5, got ??FA?@?????"??{?_????Q}b?B??

**Comment by folbricht** [comment]
Thank you. This error suggests the issue is actually in desync. I'll need to review that code-path. Would you be able to provide more details of how you repro this?
- Does it always fail in the same place/same file?
- How large is the file and is there anything unusual about it (mostly 0 bytes or such)?
- Would you be able to provide an example file I could use that triggers the problem?

**Comment by limbo127** [comment]
Does it always fail in the same place/same file?
-> no, first desync make  produce  error on one chunk, then delete this chunk, redo a desync make : no error on the same chunk id but on other one : 
[wso-retd2-72615d80-d797-11dd-b984-c03fd56fec58]desync make -m 64:256:512 -n 3 -s /data/cache2/store /data/c5df8a5cdd1e6e26fd7ce210c5bbf758.6e4cd4c9-5e8b-4ada-98ea-0b4643370eeb.index /data/c5df8a5cdd1e6e26fd7ce210c5bbf758.6e4cd4c9-5e8b-4ada-98ea-0b4643370eeb.raw
$?G?Z?ml?U?J3+$??{?oes not match expected hash 1b93d1735b6011d0dc51451bc3b1f92cc80b32f591cdb8bfe4ac562a54c87b32, got @??yF&7?


How large is the file and is there anything unusual about it (mostly 0 bytes or such)?
->60G of raw sparse file, with 75% of zero

Would you be able to provide an example file I could use that triggers the problem?
-> Yes, it's just  microsoft windows raw image file create by qemu

 Go version : go version go1.9.2 linux/amd64

**Comment by folbricht** [comment]
My first thought was that perhaps the file is mounted and being written to while the chunking is ongoing, but actually the code would have caught that and returned an error if that was the case (still, would be good to confirm that it's not being written to). I've been chunking similar files, much larger ones, and with up to 50 goroutines without running into that problem.

So at this point, after reviewing the code, the only explanation I have is that for some reason the zstd library used produces chunks isn't compressing correctly. So a chunk is compressed, then decompressed and the content is different. Since I believe you were able to successfully chunk large files previously, is there anything that changed? Like a different CPU, or the zstd library was updated perhaps?

I added more debugging to the branch. When it fails now, it'll write 5 files into the current dir, the compressed/decompressed chunks at different stages. If you could send me the md5sum of all of those that would help.

Try updating your zstd with `go get -u github.com/datadog/zstd` as there have been several changes recently. Then rebuild desync and try again.

In the meantime, to unblock you, it's ok to run this version multiple times.  It'll not store bad chunks but fail instead. If you run it again after failure, it should just carry on and hopefully not fail again to complete the chunking the file.

**Comment by limbo127** [comment]
Hello
No thé raw file is not mouting or using by other process during desync
make.
Only desync version change and chunk size make option.
I m trying your debug version this monday.
Thanks
Nicolas

**Comment by limbo127** [comment]
hello, 
first test : 
desync issue-37  branch last commit + zstd update : no issue on 2 tests
desync issue-37 : one error, as previous
desync master branch + zstd update : no issue 
i'm trying more tests tomorow, but it seems zstd problem.
regards, 
Nicolas

**Comment by charles-dyfis-net** [comment]
Think about it like `.gz` vs `.tar.gz` -- sometimes you just want raw contents, without needing extra wrapper/container metadata. Similarly, if you're trying to retrieve a single file, you don't *want* a format built as an archiver -- adds extra failure cases; what if it has more files in it than you expect? How do you pick one?
