### ISSUE TITLE
Fix import to stable version

### ISSUE THREAD

**Issue by limbo127** [folbricht/desync#39]
Hello, 
	"github.com/hanwen/go-fuse/fuse"
	"github.com/hanwen/go-fuse/fuse/nodefs"
"github.com/hanwen/go-fuse/fuse/pathfs"

desync code import this, but without specify a commit or stable version  (i do not know if possible). 
And today, fuse code is buggy ( commit 24 july about lock) , then desync mount-index does not work anymore for our utilisation.

Regards, 
Nicolas

**Comment by folbricht** [comment]
What kind of issue are you seeing with that? Please describe what's broken in more detail.

There's not much we can do with regards to linking to a stable version. There're no consistent versioning/branches/tags we could use with gopkg.in and introducing dependency management seems over-the-top for just this issue. The cleanest solution would be to figure out what's failing and fix the go-fuse library (or desync if it turns out to be on this side). There's active development with at least one commit after this issue was opened, might be worth a try. As a workaround until this gets addressed, you could simply checkout an older revision in your working copy ($GOPATH/src/github.com/hanwen/go-fuse/).

**Comment by limbo127** [comment]
hello, 
fuse-go seems to implement some lock function, but now with using a qemu on image mount by desync mount-index, qemu/libvirt exit with : Failed to lock byte 100 
regards, 
Nicolas

**Comment by limbo127** [comment]
And i agree with you about dependency management, but the recent node.js breakdown ..
perhaps include a static version of dependency in your tree ?
regards, 
Nicolas

**Comment by limbo127** [comment]
patch is commiting in fuse-go
