### ISSUE TITLE
impossible to get desync binary

### ISSUE THREAD

**Issue by limbo127** [folbricht/desync#4]
Hello, 
go get -u github.com/folbricht/desync 

get src , but not installation of tools
go build does not work, go build github.com/folbricht/desync/cmd/desync/   not work 

go version go1.9.2 linux/amd64

what my mistake ?
Regards, 
Nicolas Prochazka

**Comment by charles-dyfis-net** [comment]
What does "not work" mean in each of these contexts?

When I run `go build github.com/folbricht/desync/cmd/desync`, the result is a `desync` binary in my current directory. Do you get an error?

**Comment by folbricht** [comment]
@limbo127 The command to download *and* install is actually `go get -u github.com/folbricht/desync/cmd/desync` which I just fixed in the docs. That should drop the binary into $GOPATH/bin.

As for the build issue, please provide more details like the OS you're trying to build it on as well as the errors you're seeing.

**Comment by limbo127** [comment]
Hello, i do not known very well go but i can build other project without
problem.
With desync, build process does not create the bin, and does return
nothing, verbose mode does not return anything
Regards
Nicolas


Le sam. 20 janv. 2018 à 04:40, folbricht <notifications@github.com> a
écrit :

**Comment by limbo127** [comment]
ok, it's working with the new path
thanks
nicolas
