### ISSUE TITLE
chunk-server slow under heavy load

### ISSUE THREAD

**Issue by folbricht** [folbricht/desync#41]
As reported by @limbo127, a HTTP chunk-server under heavy load (2k clients requesting the same 10 chunks concurrently) can become very slow to respond which may cause client-side timeouts after 60s. This happens even with chunks being available in a local store.

Timings from local testing:

Concurrent requests | Time to complete
------------ | -------------
5k | 3.6s
10k | 16s
20k | 1m15s

It was suggested that perhaps https://github.com/valyala/fasthttp may be helpful since it can limit the number of concurrent requests.

**Comment by folbricht** [comment]
This doesn't appear to be related to the HTTP implementation. It's more a matter of performance tuning network parameters on the servers. One setting that worked well testing on a laptop was `sysctl net.core.somaxconn=4096` which brought down the time to process 20k concurrent requests to 20s. There are other settings that could be tweaked on the chunk-server. Some examples can be found in https://gist.github.com/techgaun/958e117b730634fa8128

For anyone wanting to try it out, there is now a `fasthttp` branch that contains an experimental (largely untested) implementation using https://github.com/valyala/fasthttp which seems to be a little faster, but doesn't by itself address the original issue.

**Comment by limbo127** [comment]
Hello, 
In our case, sysctl kernel parameters are already setting. 
I do not think it's a desync relative problem , put a network issue in general for us : 
A lot of client, a lot of hierarchical desync cache chunk-server and network  bandwitch and latence issue

- N desync mount-index --- lan--> chunk-server 1 ---wan1---> chunk-server A---> wan2 ---> chunk-serverB

- N desync mount-index --- lan--> chunk-server 2 ---wan1---> chunk-server A---> wan2 ---> chunk-serverB
....
We are observing chunk-server A  kept a lot of connection, because it must answer to 1,2 and forward to B. In this case, after some time,  chunk-server A cannot serve any requests , because load average ( number of gorouting and // requests is too much important ) .  fastHttp can manage a pool of connection, we are trying to test it. 
Thanks for this branch.
Nicolas

**Comment by limbo127** [comment]
ok, I did not understand the importance of -n in this configuration, we are testing with a big -n.
regards,
Nicolas

**Comment by folbricht** [comment]
@limbo127 Did setting a higher -n on the proxying chunk servers help or is there anything else that worked for you which may be useful to be added to this thread before we close it.

**Comment by limbo127** [comment]
Yes.
