### ISSUE TITLE
Deal with conflicting writes to S3

### ISSUE THREAD

**Issue by folbricht** [folbricht/desync#47]
Right now it's possible for one or more instances of desync writing the same chunk concurrently to S3. While consistency is guaranteed by S3, some of these write operations may return a failure which at the moment will fail the whole operation since it doesn't distinguish between a conflict (which could be ignored) and other failures during writing as per https://github.com/folbricht/desync/blob/badf03f3ea7c4bd51f89a16523ce1d07223756dc/s3.go#L88

- Figure out what kind of error is returned by the minio client library when a write conflict is encountered
- If that error is returned by the write operation, ignore it and return success

@angelcar Something tells me you might already know the answer to the above... :)

**Comment by angelcar** [comment]
Hmm, 
Minio doesn't seem to catch conflicting writes explicitly.

I tried to repro this by making a code change to have all the go routines store the same chunk (I'm just saving the first produced chunk and storing that one all the time).

I am using 20 goroutines and I see some errors occasionally. The errors are network errors, which is not what I was expecting.

These are some of the error types I logged (ip details omitted):

* `Put https://<bucket_name>.s3-us-west-2.amazonaws.com/<test-store-name>/6232/6232a1840f826e9e445598661b31d4e588b5dbcc1abc8f070dd09f908ab481d7.cacnk: net/http: HTTP/1.x transport connection broken: write tcp xx.xx.xx.xx:59779->yy.yy.yy.yy:443: write: broken pipe`

* `Put https://<bucket_name>.s3-us-west-2.amazonaws.com/<test-store-name>/6232/6232a1840f826e9e445598661b31d4e588b5dbcc1abc8f070dd09f908ab481d7.cacnk: read tcp xx.xx.xx.xx:59839->yy.yy.yy.yy:443: read: connection reset by peer.`

* `Put https://<bucket_name>.s3-us-west-2.amazonaws.com/<test-store-name>/6232/6232a1840f826e9e445598661b31d4e588b5dbcc1abc8f070dd09f908ab481d7.cacnk: net/http: HTTP/1.x transport connection broken: http: ContentLength=5264845 with Body length 5260749`


So, put objects fails with different errors at different times due to conflicting writes. I think this definitely needs more investigation, but I am guessing the relevant error in the above list is the first one since it's the only one the mentions `write`. The other errors might be because I am bombarding s3 with exactly the same request multiple times, which is more than just a conflicting write. 

Do you have a particular file to repro this more naturally?

**Comment by folbricht** [comment]
That is rather unexpected. Was hoping for a more consistent error that could be handled gracefully. While I haven't seen this happen myself (mainly because I don't use a real S3 store for testing and usually small files), it's actually quite likely someone runs into this without even trying. Here's how that would happen:
- Take a blank store
- Chunk a file that is either all 0 bytes or has a large 0-byte block near the start of the file

What happens in this situation (with the current code on master) is that this file would be chunked at max-chunk-size, so there would be many consecutive null-chunks in the index. Then when the file is chopped up according to the index, the first `n` goroutines would be trying to store the same chunk. De-duping the index before chopping the file would solve this situation, at least for a single desync instance operating on the s3 store. If there're more, it could still happen. Anyway, to make a real sample to repro this, `dd if=/dev/zero of=inputfile bs=1M count=1000` or similar should do, then run the `make` command with a large number of goroutines to trigger the collision.

**Comment by folbricht** [comment]
https://github.com/folbricht/desync/commit/48cd6904732e75330ba5b562a9a56243f58d7009 should be a workaround for this issue, at least in the case of single instances of desync. It avoids several goroutines trying to store the same chunk which could lead to one or several of them failing when using S3.

Unfortunately there's a bit of magic here making assumptions about what the caller does in the case of any other failure. It's assuming the caller will not re-try a failed chunk since then it'd be marked as done in the map already. Could have it removed from the map in case of failure perhaps.

Thoughts? Too much magic?

**Comment by folbricht** [comment]
https://github.com/folbricht/desync/pull/54 works around the issue in case of single desync instances. It's still possible to occur when multiple instances of desync attempt to store the same chunk at the same time, but the chance of that happening is very very small. Small enough to not warrant further workarounds. We can re-visit if anyone's willing to put in the effort, or when minio returns a consistent error that can be used to detect and handle conflicting writes.
