### ISSUE TITLE
Cannot extract directly to Linux block device

### ISSUE THREAD

**Issue by jkirkwood** [folbricht/desync#73]
I'm trying to use desync to write directly to a USB flash drive partition enumerated as `/dev/sdb2`. I've been playing around with the cli tool to see how this works. So far I've been able to generate a local store and .caibx file using the `make` command, but cannot `extract` the data on to the USB drive.

When I run this command:

`desync extract -k -s store index.caibx /dev/sdb2`

I get this error:

`Error: truncate /dev/sdb2: invalid argument`

I've narrowed down the issue to the call to `os.Truncate` in `assemble.go`. If I remove these lines everything works as expected.

Is there some kind of special handling that should take place for block devices? Can we just make sure the target device is large enough instead of truncating it?

**Comment by charles-dyfis-net** [comment]
I believe this is a new bug -- until it's resolved, you should be able to use `desync cat`.

**Comment by jkirkwood** [comment]
How open are you to updating `extract` to work with block devices? The `cat` command works, but `extract` provides a lot of nice features (progress bar, seeds, etc).

**Comment by folbricht** [comment]
Not opposed to it at all. Going to have to find a nice way that doesn't increase complexity. For example to support the `-k` option for in-place file extraction, `os.Truncate()` is going to be necessary in case the existing file is larger than it should be. So likely going to need to determine if the target is a file or block device in the extract command.

Alternatively, the `cat` command could get a progress bar writing to STDOUT. Seeds would be possible too, but much more effort.

I'm going to take a look, might turn out to be straightforward.

**Comment by folbricht** [comment]
@jkirkwood Would you be able to try out the issue-73 branch before I merge that? It'll still require the `-k` option when extracting, but it's no longer going to truncate it, and also not use optimizations that are meant for blank files.

**Comment by jkirkwood** [comment]
@folbricht I had a chance to play around with this a bit today and everything appears to be working. I tested with both block devices and normal files, and with different seed/store configurations.

Thanks for working this out.

**Comment by folbricht** [comment]
Thanks for taking a look. Will be merging it to master shortly.

Keep in mind that the way the device is written to differs between `cat` and `extract -k`.
- `cat` just writes to the device sequentially, the whole file from start to finish.
- `extract -k` will write concurrently, but it also checks if any of the chunks are already in place. So it reads first, checks the data, and only writes if the data it read is differs. The extra read could make it a little slower, but if the data is already mostly in place, then only the difference is written, so in that case it could be faster. Also, `extract` uses seeds, one of which is the self-seed. If the data contains the same chunk or sequence of chunks multiple times, it'll be copied (involves reading from the device). On the other hand a flash-based device will wear less since only the diff is written with `extract`.
