### ISSUE TITLE
enhancement : pipable for make option

### ISSUE THREAD

**Issue by limbo127** [folbricht/desync#8]
Hello, 
Is it possible to implement pipable mode for make command ? 
For example : 
cat blob.image | desync make index  

regards, 
Nicolas Prochazka

**Comment by limbo127** [comment]
desync make index < /tmp/pipe

**Comment by charles-dyfis-net** [comment]
You'd lose the ability to parallelize the chunking (irreparably, since a FIFO isn't seekable), and some logic would need to have separate paths between the cases unless it cached contents read from the pipe to a temporary file on disk (since we can't afford to cache chunks which have been read but not assembled in memory in the parallel path, at least one side of the logic needs to store only offset/length references and be able to retrieve contents later).

With those limitations, is the feature still worth it?

(Also, the next thing I work on will probably be mount support for catar/caidx, so unless you build a PR for this yourself or Frank finds it interesting, it may be a while).

**Comment by limbo127** [comment]
you are right
regards,
nicolas
