### ISSUE TITLE
"desync tar" can bail outright on a UID lookup failure

### ISSUE THREAD

**Issue by charles-dyfis-net** [folbricht/desync#88]
```
# desync tar out.catar /mnt
user: lookup userid 0: no such file or directory
```

The above was observed in a sandboxed environment without an `/etc/passwd`.

If `/etc/passwd` is created but empty, the result is a bit different:

```
user: unknown userid 0
```

I would expect desync to continue (with numeric IDs only) should username lookup fail.

**Comment by folbricht** [comment]
The failure isn't actually related to `tar` at all. It happens when desync tries to find the default config file location which involves a lookup of the current user. PR https://github.com/folbricht/desync/pull/89 should address this, but I'm not entirely sure since I was only able to repro one of the failures. A retry with that fix would be much appreciated.

**Comment by charles-dyfis-net** [comment]
Huh. That's... interesting.

As a user, when I change the value of `HOME`, I expect tools to honor that value from the environment and not try to perform an account-database lookup... but then again, maybe that doesn't make sense on Windows?

**Comment by charles-dyfis-net** [comment]
(Which is to say that my proposed fix would be to use `${HOME:-}/.config/desync`, and skip the account-database look entirely).

**Comment by folbricht** [comment]
That does seem like the simpler solution, though there'll need to be some OS-specific code since the equivalent on Windows is `HOMEDRIVE` + `HOMEDIR`. Going to update the PR accordingly.

**Comment by folbricht** [comment]
Resolved in https://github.com/folbricht/desync/pull/89
