### ISSUE TITLE
desync / bad chunk create

### ISSUE THREAD

**Issue by limbo127** [folbricht/desync#97]
Hello, 
we have sometime some bad chunk, and it' difficult to understand why, perhaps a concurrent write , is it possible ?

client 1 ----> chunk-server 1 -----> chunk-server2 
client 2 ----> chunk-server1  ------> chunk-server2
client n ---> chunk-server1 ---> chunk-server2

what happening if client 1 and client ask for the same chunk as the same time ? 
is it possible, in this case , that on chunk-server1 chunk are corrupts ? 

Regards, 
Nicolas Prochazka

**Comment by charles-dyfis-net** [comment]
desync uses a tempfile-write-and-rename pattern, so concurrent writes are
safe.

**Comment by limbo127** [comment]
Yes I known because I've already ask for this kind of issue, so how is
possible, perhaps a file system ( f2fs) cache  issue ?
regards,
Nicolas

Le lun. 25 févr. 2019 à 13:32, Charles Duffy <notifications@github.com> a
écrit :

> desync uses a tempfile-write-and-rename pattern, so concurrent writes are
> safe.
>

**Comment by charles-dyfis-net** [comment]
I'd need to dig into f2fs to speak to it specifically, but anything that
doesn't force a close() to be flushed before reporting success could cause
data to be visible while invalid.

**Comment by folbricht** [comment]
This could also be a resurgence of https://github.com/folbricht/desync/issues/37 (zstd failure on your HW). There used to be a double-check in the code to look for it which made it a little slower. That was removed in a refactoring since it seemed you were no longer impacted after updating zstd. If this happens frequently enough, I could make you another special version of desync to help hunt this problem. I could also be related to #96 in some way. If you could repro that one first and let us know what the output looks like (stacktrace), that would be very useful to narrow it a bit more.

When you see a bad chunk, is it blank (0 bytes)?

**Comment by limbo127** [comment]
Yes i'm trying, but for now can not reproduce #96 with trace. And  #37, yes
an update of zstd seems to correct this issue.
nicolas

Le lun. 25 févr. 2019 à 15:30, folbricht <notifications@github.com> a
écrit :

**Comment by folbricht** [comment]
In case of the bad chunks. Are those bad chunks actually stored on disk or do they get reported during reading only and what's on disk is consistent?

You can check the consistency of a (compressed) chunk on disk manually like so:

```
cat store/<prefix>/<chunkid>.cacnk | zstd -d | openssl sha512-256
```
The result should match the chunkID.

**Comment by limbo127** [comment]
no more at this time .
Nicolas
